version: 0.2

env:
  variables:
    ACCOUNT_ID: 288206953113
    REGION: ap-south-1
    REPO_NAME: brain-tasks-app
    REPO_URI: 288206953113.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app:latest .
      - docker tag brain-tasks-app:latest $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPO_URI:latest
