version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install || true

      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 288206953113.dkr.ecr.ap-south-1.amazonaws.com

  pre_build:
    commands:
      - echo Installing Node.js dependencies...
      - npm install

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo Setting up kubeconfig for EKS...
      - mkdir -p ~/.kube
      - |
        cat <<EOF > ~/.kube/config
        apiVersion: v1
        clusters:
        - cluster:
            server: ${EKS_CLUSTER_ENDPOINT}
            certificate-authority-data: ${EKS_CLUSTER_CA}
          name: ${EKS_CLUSTER_NAME}
        contexts:
        - context:
            cluster: ${EKS_CLUSTER_NAME}
            user: aws
          name: ${EKS_CLUSTER_NAME}
        current-context: ${EKS_CLUSTER_NAME}
        kind: Config
        preferences: {}
        users:
        - name: aws
          user:
            exec:
              apiVersion: client.authentication.k8s.io/v1beta1
              command: aws
              args:
                - "eks"
                - "get-token"
                - "--region"
                - "ap-south-1"
                - "--cluster-name"
                - "${EKS_CLUSTER_NAME}"
        EOF

      - echo Validating Kubernetes files...
      - kubectl apply --dry-run=client -f k8s/

      - echo Deploying to EKS...
      - kubectl apply -f k8s/

artifacts:
  files:
    - '**/*'

