version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    IMAGE_REPO_NAME: brain-tasks-app
    EKS_CLUSTER_NAME: brain-tasks
  secrets-manager:
    KUBECONFIG_DATA: "brain-tasks/kubeconfig:config"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install || true

      - echo Installing kubectl...
      - K8S_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
      - echo "Using kubectl version: $K8S_VERSION"
      - curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 288206953113.dkr.ecr.ap-south-1.amazonaws.com

  pre_build:
    commands:
      - echo Setting IMAGE_TAG...
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 288206953113.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 288206953113.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo Setting up kubeconfig from Secrets Manager...
      - mkdir -p ~/.kube
      - echo "$KUBECONFIG_DATA" > ~/.kube/config

      - echo Validating Kubernetes manifests...
      - kubectl apply --dry-run=client -f k8s/

      - echo Applying manifests to EKS...
      - kubectl apply -f k8s/

artifacts:
  files:
    - '**/*'
