apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: brain-tasks-app
=======
  name: brain-tasks-deployment
  labels:
    app: brain-tasks
>>>>>>> 1fd938c (Added Dockerfile, Kubernetes YAMLs, buildspec, appspec)
spec:
  replicas: 2
  selector:
    matchLabels:
<<<<<<< HEAD
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
      - name: brain-tasks-container
        image: <your_repo_uri>:latest
        ports:
        - containerPort: 3000
=======
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
      - name: brain-tasks
        image: 288206953113.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-0a387685215d:latest
        ports:
      - containerPort: 80
>>>>>>> 1fd938c (Added Dockerfile, Kubernetes YAMLs, buildspec, appspec)
