apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: LoadBalancer
  selector:
<<<<<<< HEAD
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
=======
    app: brain-tasks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
>>>>>>> 1fd938c (Added Dockerfile, Kubernetes YAMLs, buildspec, appspec)
